/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System;
using System.Net.Http;

namespace AfterShipTracking
{
    public class CourierConnectionService : BaseResourceService
    {
        IHttpClient HttpClient;

        public CourierConnectionService(IHttpClient httpClient)
        {
            this.HttpClient = httpClient;
        }

        public CourierConnection PutCourierConnectionsById(string id,  PutCourierConnectionsByIdOptions? options = null)
        {
            string path = $"/tracking/2025-04/courier-connections/{id}";
            if (string.IsNullOrEmpty(id))
            {
               throw ErrorCode.GenSDKError(ErrorCode.REQUEST_ERROR,"request error"+": `id` is invalid");
            }
            Request request = new Request(
                new HttpMethod("PATCH"),
                path,
                options
            );

            var response = this.HttpClient.MakeRequest(request);
            return ProcessData<CourierConnection>(response);
        }
        public GetCourierConnectionsResponseCourierConnectionListData GetCourierConnections( GetCourierConnectionsOptions? options = null)
        {
            string path = $"/tracking/2025-04/courier-connections";
            Request request = new Request(
                HttpMethod.Get,
                path,
                options
            );

            var response = this.HttpClient.MakeRequest(request);
            return ProcessData<GetCourierConnectionsResponseCourierConnectionListData>(response);
        }
        public CourierConnection PostCourierConnections( PostCourierConnectionsOptions? options = null)
        {
            string path = $"/tracking/2025-04/courier-connections";
            Request request = new Request(
                HttpMethod.Post,
                path,
                options
            );

            var response = this.HttpClient.MakeRequest(request);
            return ProcessData<CourierConnection>(response);
        }
        public CourierConnection GetCourierConnectionsById(string id,  GetCourierConnectionsByIdOptions? options = null)
        {
            string path = $"/tracking/2025-04/courier-connections/{id}";
            if (string.IsNullOrEmpty(id))
            {
               throw ErrorCode.GenSDKError(ErrorCode.REQUEST_ERROR,"request error"+": `id` is invalid");
            }
            Request request = new Request(
                HttpMethod.Get,
                path,
                options
            );

            var response = this.HttpClient.MakeRequest(request);
            return ProcessData<CourierConnection>(response);
        }
        public CourierConnection DeleteCourierConnectionsById(string id,  DeleteCourierConnectionsByIdOptions? options = null)
        {
            string path = $"/tracking/2025-04/courier-connections/{id}";
            if (string.IsNullOrEmpty(id))
            {
               throw ErrorCode.GenSDKError(ErrorCode.REQUEST_ERROR,"request error"+": `id` is invalid");
            }
            Request request = new Request(
                HttpMethod.Delete,
                path,
                options
            );

            var response = this.HttpClient.MakeRequest(request);
            return ProcessData<CourierConnection>(response);
        }
    }
}

